[package]
name = "mandelbrot"
version = "0.2.0"
authors = ["Thomas Röggla <tom@lichtfragmente.com>"]
edition = "2021"

[dependencies]
image = "0.24.2"
num = "0.4.0"
pbr = "1.0.4"
threadpool = "1.8.1"
time = "0.3.9"
clap = { version = "3.1.18", features = ["derive"] }
