[package]
name = "mandelbrot"
version = "0.2.0"
authors = ["Thomas Röggla <tom@lichtfragmente.com>"]

[dependencies]
argparse = "0.2.2"
image = "0.24.2"
num = "0.4.0"
pbr = "1.0.4"
threadpool = "1.8.1"
time = "0.3.9"
